export { createAnthropicClient } from './client.js';
export { embed, embedBatch, EMBEDDING_DIM } from './embeddings.js';
export { retrieve, retrieveWarningLetters, retrieveNDINotifications } from './rag/retriever.js';
export { indexAll, indexWarningLetters, indexNDINotifications, indexRegulatoryChanges } from './rag/indexer.js';
export { analyzeIngredientWithRAG, classifyClaimWithRAG, getNDIGuidance, reviewLabel } from './rag/generator.js';
export type { RetrievedDocument } from './rag/retriever.js';
export type { IngredientAnalysisInput } from './prompts/ingredient-analysis.js';
export type { ClaimsClassificationInput } from './prompts/claims-classification.js';
export type { NDIGuidanceInput } from './prompts/ndi-guidance.js';
export type { LabelReviewInput } from './prompts/label-review.js';
